export const ADD_ORDER_NUMBER = "ADD_ORDER_NUMBER";
export const ADD_ORDER_TYPE = "ADD_ORDER_TYPE";
export const ADD_REQUEST_NUMBER = "ADD_REQUEST_NUMBER";
export const ADD_PROCESS_TYPE = "ADD_PROCESS_TYPE";

export const ADD_ORDER_COMPANY = "ADD_ORDER_COMPANY";
export const ADD_ORDER_EMPLOYEE = "ADD_ORDER_EMPLOYEE";
